services:

  vote:
    image: hamdiz0/va-vote:1.0
    ports:
      - "8000:80"

  result:
    image: hamdiz0/va-result:1.0
    ports:
      - "8001:80"

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data" # create a volume to store data locally

  worker:
    image: hamdiz0/va-worker:1.0

volumes:
  db-data: # persist postgres data locally
  
