services:

  vote:
    image: bensassiahmed/voting-app:vote-1.0
    ports:
      - "8000:80"

  result:
    image: bensassiahmed/voting-app:result-1.0
    ports:
      - "8001:80"

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"

  worker:
    image: bensassiahmed/voting-app:worker-1.0  

volumes:
  db-data:
  
