---
# vote-deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    name: vote-deployment
    app: vote-app

spec:
  replicas: 3
  selector:
    matchLabels:
      name: vote-pod
      app: vote-app
  template:
    metadata:
      labels:
        name: vote-pod
        app: vote-app
    spec:
      containers:
        - name : vote
          image: hamdiz0/va-vote:<<VERSION>> # the script passes the version automaticly throught this variable
          ports :
          - containerPort: 80

---
# vote-service

apiVersion: v1
kind: Service
metadata:
  name: vote-svc

spec:
  selector:
    name: vote-pod
    app: vote-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000