---
# worker-deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
    app: vote-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: vote-app
  template:
    metadata:
      labels:
        name: worker-pod
        app: vote-app
    spec:
      containers:
        - name : worker
          image: hamdiz0/va-worker:<<VERSION>> 